version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/jenkins/batch/deploy

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root